添加 WithBasicAuth (#1)
* feat(requests): 添加基本认证功能

- 在 Session 接口中添加 WithBasicAuth 方法
- 实现基本认证逻辑，生成 Base64 编码的认证头
- 更新单元测试，增加对基本认证功能的测试


* ci: 更新工作流以包含代码覆盖率检查和自动审批

- 在 go-test.yml 中添加代码覆盖率检查步骤
- 如果覆盖率低于 90%，则失败
- 新增 Auto Approve PR 工作流，自动审批通过测试的 PR

diff --git a/.github/workflows/go-test.yml b/.github/workflows/go-test.yml
--- a/.github/workflows/go-test.yml
+++ b/.github/workflows/go-test.yml
@@ -1,4 +1,4 @@
-name: Go
+name: Go Test
 
 on:
   push:
@@ -27,7 +27,18 @@ jobs:
     - name: Run tests
       run: |
         go test -coverprofile=coverage.txt ./...
-        go tool cover -func=coverage.txt
+
+    - name: Parse and check coverage
+      id: check-coverage
+      run: |
+        grep -v '/example/' coverage.txt > filtered_coverage.out
+        COVERAGE=$(go tool cover -func=filtered_coverage.out | grep total | awk '{print $3}' | tr -d '%')
+        echo "Coverage: $COVERAGE%"
+        if (( $(echo "$COVERAGE < 90" | bc -l) )); then
+          echo "Coverage is below the required threshold of 90%"
+          exit 1
+        fi
+      shell: bash
 
     - name: Upload coverage reports to Codecov
       uses: codecov/codecov-action@v5
